#include "PPCAOTAssemblyGen.h"
#include <fstream>
#include <iomanip>
#include <sstream>
#include <fmt/format.h>

namespace PPCAOTAssemblyGen
{

static void EmitBytesAsDirectives(std::ostream& out, const uint8_t* data, size_t size);
static void EmitBytesWithRelocations(std::ostream& out, const AOTFunctionRecord& func);

std::string FormatAddress(uint32_t address)
{
	return fmt::format("{:08x}", address);
}

bool GenerateAssembly(const AOTCache& cache, const std::filesystem::path& outputPath,
					  const std::string& symbolPrefix)
{
	std::ofstream out(outputPath);
	if (!out.is_open())
		return false;

	out << "// Auto-generated AOT function assembly\n";
	out << "// Generated from AOT cache with " << cache.functions.size() << " functions\n";
	out << "// Title ID: 0x" << std::hex << cache.header.titleId << std::dec << "\n";
	out << "// DO NOT EDIT - this file is generated by the AOT compiler\n\n";

	out << ".text\n";
	out << ".align 4\n\n";

	for (size_t funcIdx = 0; funcIdx < cache.functions.size(); funcIdx++)
	{
		const auto& func = cache.functions[funcIdx];
		std::string funcSymbol = symbolPrefix + FormatAddress(func.ppcAddress);

		out << "// PPC function at 0x" << FormatAddress(func.ppcAddress)
			<< " (size: 0x" << FormatAddress(func.ppcSize) << ")\n";

		// Alignment
		if (func.codeAlignment > 4)
			out << ".align " << (func.codeAlignment == 16 ? 4 : 3) << "\n";

		// Global symbol for the function start
		out << ".globl _" << funcSymbol << "\n";
		out << "_" << funcSymbol << ":\n";

		// Emit entry point labels for sub-entry points within the function
		for (const auto& ep : func.entryPoints)
		{
			if (ep.nativeOffset > 0)
			{
				std::string epSymbol = symbolPrefix + "ep_" + FormatAddress(ep.ppcAddress);
				out << "// Entry point for PPC 0x" << FormatAddress(ep.ppcAddress)
					<< " at native offset 0x" << std::hex << ep.nativeOffset << std::dec << "\n";
			}
		}

		// Check if there are relocations that need special handling
		if (func.relocations.empty())
		{
			// No relocations — emit all bytes directly
			EmitBytesAsDirectives(out, func.machineCode.data(), func.machineCode.size());
		}
		else
		{
			// Has relocations — emit bytes in chunks, inserting relocation references
			EmitBytesWithRelocations(out, func);
		}

		out << "\n";
	}

	return out.good();
}

static void EmitBytesAsDirectives(std::ostream& out, const uint8_t* data, size_t size)
{
	constexpr size_t BYTES_PER_LINE = 16;
	for (size_t i = 0; i < size; i += BYTES_PER_LINE)
	{
		out << "    .byte ";
		size_t lineEnd = std::min(i + BYTES_PER_LINE, size);
		for (size_t j = i; j < lineEnd; j++)
		{
			if (j > i)
				out << ", ";
			out << fmt::format("0x{:02x}", data[j]);
		}
		out << "\n";
	}
}

static void EmitBytesWithRelocations(std::ostream& out, const AOTFunctionRecord& func)
{
	// Sort relocations by offset
	auto relocations = func.relocations;
	std::sort(relocations.begin(), relocations.end(),
		[](const auto& a, const auto& b) { return a.offsetInCode < b.offsetInCode; });

	size_t currentOffset = 0;
	for (const auto& reloc : relocations)
	{
		// Emit bytes before this relocation
		if (reloc.offsetInCode > currentOffset)
		{
			EmitBytesAsDirectives(out, func.machineCode.data() + currentOffset,
								 reloc.offsetInCode - currentOffset);
		}

		if (reloc.type == AOTRelocationType::AbsoluteAddress64)
		{
			// AArch64 MOVZ+MOVK sequence for 64-bit immediate is 16 bytes (4 instructions).
			// Replace with ADRP+LDR sequence that references the symbol via GOT.
			// For simplicity, emit as .quad with a linker reference, padded to match original size.
			out << "    // Relocation: " << reloc.symbolName << " (absolute address)\n";
			out << "    adrp x25, _" << reloc.symbolName << "@GOTPAGE\n";
			out << "    ldr  x25, [x25, _" << reloc.symbolName << "@GOTPAGEOFF]\n";
			// Pad remaining bytes with NOPs to maintain code alignment
			// Original MOVZ+MOVK+MOVK+MOVK = 16 bytes, ADRP+LDR = 8 bytes, so 2 NOPs
			out << "    nop\n";
			out << "    nop\n";
			currentOffset = reloc.offsetInCode + 16; // skip the 4 original MOV instructions
		}
		else
		{
			// Unknown relocation type — emit original bytes
			out << "    // WARNING: Unknown relocation type at offset 0x"
				<< std::hex << reloc.offsetInCode << std::dec << "\n";
			EmitBytesAsDirectives(out, func.machineCode.data() + reloc.offsetInCode, 4);
			currentOffset = reloc.offsetInCode + 4;
		}
	}

	// Emit remaining bytes after last relocation
	if (currentOffset < func.machineCode.size())
	{
		EmitBytesAsDirectives(out, func.machineCode.data() + currentOffset,
							 func.machineCode.size() - currentOffset);
	}
}

bool GenerateRegistrationTable(const AOTCache& cache, const std::filesystem::path& outputPath,
							   const std::string& symbolPrefix)
{
	std::ofstream out(outputPath);
	if (!out.is_open())
		return false;

	out << "// Auto-generated AOT function registration table\n";
	out << "// Generated from AOT cache with " << cache.functions.size() << " functions\n";
	out << "// Title ID: 0x" << std::hex << cache.header.titleId << std::dec << "\n";
	out << "// DO NOT EDIT - this file is generated by the AOT compiler\n\n";

	out << "#include \"Cafe/HW/Espresso/Recompiler/AOT/PPCAOTLoader.h\"\n";
	out << "#include <cstdint>\n\n";

	// Extern declarations for each function symbol
	for (const auto& func : cache.functions)
	{
		std::string funcSymbol = symbolPrefix + FormatAddress(func.ppcAddress);
		out << "extern \"C\" void " << funcSymbol << "();\n";
	}
	out << "\n";

	// Function table
	out << "extern \"C\" const AOTFunctionEntry g_aotFunctionTable[] = {\n";
	for (size_t i = 0; i < cache.functions.size(); i++)
	{
		const auto& func = cache.functions[i];
		std::string funcSymbol = symbolPrefix + FormatAddress(func.ppcAddress);
		out << "    { 0x" << FormatAddress(func.ppcAddress)
			<< ", reinterpret_cast<void*>(" << funcSymbol << ") },\n";
	}
	out << "};\n\n";

	out << "extern \"C\" const size_t g_aotFunctionCount = "
		<< cache.functions.size() << ";\n\n";

	// Entry point table — maps each PPC entry address to its function and native offset
	out << "extern \"C\" const AOTEntryPointEntry g_aotEntryPointTable[] = {\n";
	size_t totalEntryPoints = 0;
	for (size_t funcIdx = 0; funcIdx < cache.functions.size(); funcIdx++)
	{
		const auto& func = cache.functions[funcIdx];
		for (const auto& ep : func.entryPoints)
		{
			out << "    { 0x" << FormatAddress(ep.ppcAddress)
				<< ", " << funcIdx
				<< ", 0x" << std::hex << ep.nativeOffset << std::dec << " },\n";
			totalEntryPoints++;
		}
	}
	out << "};\n\n";

	out << "extern \"C\" const size_t g_aotEntryPointCount = "
		<< totalEntryPoints << ";\n";

	return out.good();
}

bool GenerateAll(const AOTCache& cache, const GeneratorOptions& options)
{
	bool success = true;

	if (options.generateAssembly)
	{
		auto asmPath = options.outputDir / "aot_functions.s";
		if (!GenerateAssembly(cache, asmPath, options.symbolPrefix))
			success = false;
	}

	if (options.generateRegistrationTable)
	{
		auto tablePath = options.outputDir / "aot_table.cpp";
		if (!GenerateRegistrationTable(cache, tablePath, options.symbolPrefix))
			success = false;
	}

	return success;
}

} // namespace PPCAOTAssemblyGen
